kind:           Deployment          
apiVersion:     apps/v1           

metadata:
    name:       deployment-wp

spec:
    replicas: 2
    
    selector:
        matchLabels:
            plantilla: wp
    
    template:
        metadata:
            name:       pod-template-ivan-wp
            labels:
                plantilla: wp
        
        spec:
            containers:
                - 
                    image:              bitnami/wordpress:latest
                    imagePullPolicy:    IfNotPresent
                    name:               contenedor
                    volumeMounts:
                        - name: datos
                          mountPath: /bitnami/wordpress 
                    env:
                        - name: WORDPRESS_DATABASE_HOST
                          value: mariadb:3306
                        - name: WORDPRESS_DATABASE_USER
                          valueFrom:
                            secretKeyRef:
                              name: datos-wp
                              key: user
                        - name: WORDPRESS_DATABASE_PASSWORD
                          valueFrom:
                            secretKeyRef:
                              name: datos-wp
                              key: password
                        - name: WORDPRESS_DATABASE_NAME
                          valueFrom:
                            secretKeyRef:
                              name: datos-wp
                              key: db

            volumes:
                - name: datos
                  persistentVolumeClaim:
                    claimName: datos-wp                              
                    
                    
                    
                    
                    
                    
                    