kind:           Service          
apiVersion:     v1           

metadata:
    name:       miapp

spec:
    type: NodePort # ClusterIP
    ports:
        - port: 8080
          targetPort: 80
          nodePort: 31111
    selector:
        plantilla: nginx
